<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  
	<ItemGroup>
	  <ProjectReference Include="..\DragonFly.API.Core\DragonFly.API.Core.csproj" />
	  <ProjectReference Include="..\DragonFly.Core\DragonFly.Core.csproj" />
	</ItemGroup>
  
	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
	  <PackageReference Update="MinVer" Version="8.0.0" />
	</ItemGroup>
</Project>
