name: .NET Core

on: 
  release:
    types:
      - published
      - edited

jobs:
  dragonfly:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release "./src/DragonFly.sln"
    - name: Run unit tests
      run: dotnet test "./src/DragonFly.sln"
    - name: Create the package
      run: dotnet pack --configuration Release "./src/DragonFly.sln"
    - name: Publish "DragonFly.AspNetCore" to nuget
      run: dotnet nuget push "./src/DragonFly.AspNetCore/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.API" to nuget
      run: dotnet nuget push "./src/DragonFly.API/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.API.Client" to nuget
      run: dotnet nuget push "./src/DragonFly.API.Client/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.API.Core" to nuget
      run: dotnet nuget push "./src/DragonFly.API.Core/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}    
    - name: Publish "DragonFly.Core" to nuget
      run: dotnet nuget push "./src/DragonFly.Core/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.Proxy" to nuget
      run: dotnet nuget push "./src/DragonFly.Proxy/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}      
    - name: Publish "DragonFly.Proxy.Attributes" to nuget
      run: dotnet nuget push "./src/DragonFly.Proxy.Attributes/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}      
    - name: Publish "DragonFly.ImageWizard" to nuget
      run: dotnet nuget push "./src/DragonFly.ImageWizard/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.BlockField.Core" to nuget
      run: dotnet nuget push "./src/DragonFly.BlockField.Core/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.BlockField" to nuget
      run: dotnet nuget push "./src/DragonFly.BlockField/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.BlockField.Client" to nuget
      run: dotnet nuget push "./src/DragonFly.BlockField.Client/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}    
    - name: Publish "DragonFly.Client" to nuget
      run: dotnet nuget push "./src/DragonFly.Client/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}      
    - name: Publish "DragonFly.ApiKeys.Core" to nuget
      run: dotnet nuget push "./src/DragonFly.ApiKeys.Core/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.ApiKeys" to nuget
      run: dotnet nuget push "./src/DragonFly.ApiKeys/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.ApiKeys.Client" to nuget
      run: dotnet nuget push "./src/DragonFly.ApiKeys.Client/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}      
    - name: Publish "DragonFly.Identity.Core" to nuget
      run: dotnet nuget push "./src/DragonFly.Identity.Core/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.Identity" to nuget
      run: dotnet nuget push "./src/DragonFly.Identity/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
    - name: Publish "DragonFly.Identity.Client" to nuget
      run: dotnet nuget push "./src/DragonFly.Identity.Client/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}         
    - name: Publish "DragonFly.MongoDB" to nuget
      run: dotnet nuget push "./src/DragonFly.MongoDB/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
   
